### ISSUE TITLE
Osavul often improperly reports the number of players on a server

### ISSUE THREAD

**Issue by velociostrich** [Unvanquished/Osavul#1]
Steps to reproduce:
1. Start Osavul
2. Click on a server
3. If the display of the number of players matches the players visible on the right panel, click Refresh.

Rarely, if ever, does the number of players appear correct. This is taking into account the number of spectators, as well.

In addition, players on one team are often shown as spectators. See this screenshot: http://imgur.com/IbNt4

Tested with the build supplied with the Windows installer for v0.7.0 of the game.

**Comment by a3s7p** [comment]
Could not reproduce. Osavul assumes that the number of players in the table at the end of a getstatus request is equal to the number of players reported by the «P» cvar, as this is an invariant that should be maintained in the game server itself. You could try querying the game server directly by sending a 

```
\xFF\xFF\xFF\xFFgetstatus
```

datagram (with the FF bytes escaped, of course) on port 27960 via UDP and take notice of «P» and the player table in the reply to see if this actually an issue with Osavul or the server reporting incorrect info.

Alternatively, wait for the debug output setting in the next version.

In fact, the weirdness with empty player names and incorrect player numbers is probably coming from the bots and the associated client number related lossage, I'll attempt debugging that when I have time.
