### ISSUE TITLE
does not compile with clang-3.2

### ISSUE THREAD

**Issue by hasufell** [Unvanquished/Osavul#4]
https://gist.github.com/5fdf0c1e8bab68b362ce
# clang --version

clang version 3.2 (tags/RELEASE_32/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
# cat /etc/portage/env/clang

FEATURES="-ccache -buildpkg -distcc -splitdebug"
USE="clang"
CC=clang
CXX=clang++
CFLAGS="-march=core2 -O3 -Wall"
CXXFLAGS="${CFLAGS}"

**Comment by a3s7p** [comment]
What's your Qt version?

**Comment by ghost** [comment]
This might be an issue with qt. I had to pass some macro flags to get it to work under OS X. If I recall correctly qt does not enable c++11 under clang.

**Comment by hasufell** [comment]
qt-4.8.4
